// Copyright (c) 2014-2017 Coin Sciences Ltd
// Mercante code distributed under the GPLv3 license, see COPYING file.

#ifndef MERCANTEVERSION_H
#define	MERCANTEVERSION_H

#define MERCANTE_VERSION_MAJOR     1
#define MERCANTE_VERSION_MINOR     0
#define MERCANTE_VERSION_REVISION  0
#define MERCANTE_VERSION_STAGE     2
#define MERCANTE_VERSION_BUILD     2

#define MERCANTE_PROTOCOL_VERSION 10008
#define MERCANTE_PROTOCOL_SUPPORTED "10004 - 10008, 20001"


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define MERCANTE_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define MERCANTE_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define MERCANTE_BUILD_DESC "1.0 beta 2"
#define MERCANTE_BUILD_DESC_NUMERIC 10000202


#ifndef MERCANTE_BUILD_DESC
#ifdef BUILD_SUFFIX
#define MERCANTE_BUILD_DESC MERCANTE_BUILD_DESC_WITH_SUFFIX(MERCANTE_VERSION_MAJOR, MERCANTE_VERSION_MINOR, MERCANTE_VERSION_REVISION, MERCANTE_VERSION_BUILD, BUILD_SUFFIX)
#else
#define MERCANTE_BUILD_DESC MERCANTE_BUILD_DESC_FROM_UNKNOWN(MERCANTE_VERSION_MAJOR, MERCANTE_VERSION_MINOR, MERCANTE_VERSION_REVISION, MERCANTE_VERSION_BUILD)
#endif
#endif

#define MERCANTE_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef MERCANTE_FULL_VERSION
#define MERCANTE_FULL_VERSION MERCANTE_FULL_DESC(MERCANTE_BUILD_DESC, MERCANTE_PROTOCOL_VERSION)
#endif


#define MERCANTE_VERSION_CODE_PROTOCOL_THIS              0
#define MERCANTE_VERSION_CODE_PROTOCOL_MIN               1
#define MERCANTE_VERSION_CODE_PROTOCOL_MIN_DOWNGRADE     2
#define MERCANTE_VERSION_CODE_PROTOCOL_MIN_NO_DOWNGRADE  3
#define MERCANTE_VERSION_CODE_PROTOCOL_FOR_RELEVANCE     4
#define MERCANTE_VERSION_CODE_BUILD                     16
#define MERCANTE_VERSION_CODE_MIN_VALID               1000

#endif	/* MERCANTEVERSION_H */

